version: '3.4'
services:
  uni-db:
    image: postgres:latest
    restart: on-failure
    environment:
        POSTGRES_DB: unidb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" 

  universityservice:
    image: ${DOCKER_REGISTRY-}universityservice
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - uni-db
    restart: on-failure

  